name: Publish picodocs docs

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/site.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write # to use actions/deploy-pages
      pages: write # to push to a github pages site
    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2

      - run: cargo run -- build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - id: deployment
        uses: actions/deploy-pages@v4
